name: Build JJBridge V8 Engine for Windows

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'release/**'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_FORGE_SRL_OPENSOURCE }}
        run: mvn -B verify --file pom.xml -P Common,Windows
      - name: Get surefire errors for debug
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: surefire-report
          path: |
            target/surefire-reports/**
            target/surefire/**
            *surefire*
            *jvmRun*
            *hs_err*