name: Build JJBridge V8 Engine for Android

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'release/**'

jobs:
  build_and_test_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure GPG Key
        run: |
          export GPG_TTY=$(tty)
          mkdir -p ~/.gnupg/
          echo "$GPG_SIGNING_KEY" > ~/.gnupg/private.asc
          gpg --batch --import ~/.gnupg/private.asc
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-android-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-android-m2
      - name: Cache Android ndk
        uses: actions/cache@v2
        with:
          path: tools/ndk
          key: android-ndk-${{ hashFiles('**/build_Android.sh') }}
          restore-keys: android-ndk
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_FORGE_SRL_OPENSOURCE }}
        run: mvn -B verify --file pom.xml -P !Common,Android,Linux