name: Build JJBridge V8 Engine for Windows

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'release/**'

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B verify --file pom.xml -P Common,Windows
      - name: Get surefire errors for debug
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: surefire-report
          path: |
            target/surefire-reports/**
            target/surefire/**
            *surefire*
            *jvmRun*
            *hs_err*