name: Release JJBridge V8 Engine

on:
  push:
    tags:
      - 'release/**'

jobs:
  build_and_test_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-android-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-android-maven
      - name: Cache Android ndk
        uses: actions/cache@v2
        with:
          path: tools/ndk
          key: android-ndk-${{ hashFiles('**/build_Android.sh') }}
          restore-keys: android-ndk
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          export GPG_TTY=$(tty)
          mvn -B verify --file pom.xml -P !Common,Android,Linux
      - name: Get jar to release
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: |
            target/jjbridge-engine-v8-*.aar

  build_and_test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          export GPG_TTY=$(tty)
          mvn -B verify --file pom.xml -P Common,Linux
      - name: Get jar to release
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            target/jjbridge-engine-v8-*-linux.jar
            target/jjbridge-engine-v8-*-javadoc.jar
            target/jjbridge-engine-v8-*-sources.jar

  build_and_test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          export GPG_TTY=$(tty)
          mvn -B verify --file pom.xml -P Common,macOS
      - name: Get jar to release
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: |
            target/jjbridge-engine-v8-*-macos.jar

  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B verify --file pom.xml -P Common,Windows
      - name: Get jar to release
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            target/jjbridge-engine-v8-*-windows.jar

  release_current_version:
    runs-on: ubuntu-latest
    needs: [build_and_test_android, build_and_test_linux, build_and_test_macos, build_and_test_windows]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - uses: actions/download-artifact@v2
        with:
          name: android
          path: target
      - uses: actions/download-artifact@v2
        with:
          name: linux
          path: target
      - uses: actions/download-artifact@v2
        with:
          name: macos
          path: target
      - uses: actions/download-artifact@v2
        with:
          name: windows
          path: target

      - name: Set up Java 1.8 for publishing to Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Release on Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_FORGE_SRL_OPENSOURCE }}
        run: |
          export GPG_TTY=$(tty)
          mvn -B deploy --file pom.xml -P Common,!Linux -Drelease-repo=maven-central -Dexec.skip=true -Dscript.executor=echo -Dmaven.main.skip=true -Dmaven.test.skip=true -Dassembly.skipAssembly=true -Dcheckstyle.skip=true -Dspotbugs.skip=true

      - name: Set up JDK 1.8 for publishing to GitHub Package Registry
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_KEY_FORGE_SRL_OPENSOURCE }}
      - name: Release on GitHub Package Registry
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_FORGE_SRL_OPENSOURCE }}
        run: |
          export GPG_TTY=$(tty)
          mvn -B deploy --file pom.xml -P Common,!Linux -Drelease-repo=github -Dexec.skip=true -Dscript.executor=echo -Dmaven.main.skip=true -Dmaven.test.skip=true -Dassembly.skipAssembly=true -Dcheckstyle.skip=true -Dspotbugs.skip=true
